IP: "INSERT NODE IP HERE"
walletSeed: "INSERT WALLET SEED HERE"
# Don't touch walletID unless you know what you're doing
walletID: "INSERT WALLET ID FROM NODE HERE"
# Don't touch masterWallet unless you know what you're doing
masterWallet: "INSERT MASTER WALLET HERE"
mongoURI: "INSERT MONGOURI HERE"

multiplier: "100000000000000000000000000000" #banano
#multiplier: "1000000000000000000000000000000" #nano

exploreaccount: "https://creeper.banano.cc/explorer/account/" #banano
#exploreaccount: "https://nanocrawler.cc/explorer/account/" #nano
exploreblock: "https://creeper.banano.cc/explorer/block/" #banano
#exploreblock: "https://nanocrawler.cc/explorer/block/" #nano
