IP: "INSERT NODE IP HERE"
walletSeed: "INSERT WALLET SEED HERE"
# Don't touch walletID unless you know what you're doing
walletID: "INSERT WALLET ID FROM NODE HERE"
# Don't touch masterWallet unless you know what you're doing
masterWallet: "INSERT MASTER WALLET HERE"

# Database - for mongoDB, add the mongoURI (comment if using alternative)
#mongoURI: "INSERT MONGOURI HERE"

# Database - for MySQL, uncomment and populate the mysql config (comment if using alternative)
#mysqlServerName: "dbservername"
#mysqlPort: 3306
#mysqlDatabaseName: "dbname"
#mysqlUsername: "dbusername"
#mysqlPassword: "dbpassword"

allowofflinepayment: false

multiplier: "100000000000000000000000000000" #banano
#multiplier: "10000000000000000000000000" #nano

exploreaccount: "https://creeper.banano.cc/explorer/account/" #banano
#exploreaccount: "https://nanocrawler.cc/explorer/account/" #nano
exploreblock: "https://creeper.banano.cc/explorer/block/" #banano
#exploreblock: "https://nanocrawler.cc/explorer/block/" #nano
